"""Generate normal_conversations.jsonl with ~6000 everyday Q&A pairs."""
import json, random, itertools

random.seed(42)

# ---------------------------------------------------------------------------
# Raw Q&A pairs grouped by topic
# ---------------------------------------------------------------------------

pairs = []

# Science & nature
pairs += [
    ("How big is the sun?", "The sun has a diameter of about 1.39 million kilometres — roughly 109 times the diameter of Earth. Its mass accounts for about 99.86% of the total mass of the solar system."),
    ("How old is the universe?", "The universe is estimated to be about 13.8 billion years old, based on measurements of the cosmic microwave background radiation and the expansion rate of the universe."),
    ("What is the speed of light?", "The speed of light in a vacuum is approximately 299,792 kilometres per second, or about 186,282 miles per second. It is denoted by the symbol c and is a fundamental constant of nature."),
    ("Why is the sky blue?", "The sky appears blue because of a phenomenon called Rayleigh scattering. Sunlight contains all colours, but shorter blue wavelengths scatter more when they hit air molecules, spreading blue light across the sky."),
    ("What causes earthquakes?", "Earthquakes are caused by the sudden release of energy stored in Earth's crust, usually when tectonic plates shift, slip along a fault line, or collide. The point underground where the rupture starts is called the focus or hypocenter."),
    ("How do black holes form?", "Black holes most commonly form when a massive star runs out of fuel and collapses under its own gravity. If the remaining core is heavy enough, nothing — not even light — can escape its gravitational pull."),
    ("What is DNA?", "DNA (deoxyribonucleic acid) is the molecule that carries genetic instructions in all living organisms. It is structured as a double helix — two strands wound around each other — and contains the biological blueprint for building and running an organism."),
    ("How does the immune system work?", "The immune system is a network of cells, tissues, and organs that defend the body against pathogens. It has two main branches: the innate immune system, which responds quickly and non-specifically, and the adaptive immune system, which learns to recognise specific threats and builds memory for future encounters."),
    ("What is gravity?", "Gravity is a fundamental force of attraction between objects with mass. According to Einstein's general relativity, massive objects curve spacetime, and other objects follow those curves — which we experience as gravitational pull."),
    ("Why do we dream?", "The exact function of dreaming is still debated, but leading theories suggest dreams help with memory consolidation, emotional processing, and problem-solving. Most vivid dreaming occurs during REM (rapid eye movement) sleep."),
    ("What is a neutron star?", "A neutron star is the dense remnant left after a massive star explodes in a supernova. They are incredibly compact — typically about 20 km across — but contain more mass than the sun, composed almost entirely of neutrons."),
    ("How do volcanoes erupt?", "Volcanoes erupt when molten rock (magma) from deep inside Earth rises to the surface. Pressure from dissolved gases and the buoyancy of magma can cause it to force its way through cracks until it erupts as lava, ash, and gases."),
    ("What is the water cycle?", "The water cycle describes how water moves continuously through the environment: it evaporates from oceans and surfaces, rises as water vapour, condenses into clouds, falls as precipitation, runs off into rivers and groundwater, and eventually returns to the ocean."),
    ("How do planes fly?", "Planes fly because of lift generated by their wings. The wing's curved shape and angle cause air to move faster over the top than the bottom, creating lower pressure above the wing. This pressure difference produces an upward force (lift) that overcomes gravity."),
    ("What is the theory of evolution?", "Charles Darwin's theory of evolution by natural selection holds that organisms with traits better suited to their environment tend to survive and reproduce more successfully. Over many generations, beneficial traits become more common in a population, leading to change over time."),
    ("How big is the Milky Way?", "The Milky Way galaxy is estimated to be about 100,000 light-years in diameter and contains between 100 and 400 billion stars. Our solar system sits roughly 26,000 light-years from the galactic centre."),
    ("What causes the seasons?", "Seasons are caused by Earth's axial tilt of about 23.5 degrees. As Earth orbits the sun, different hemispheres are tilted toward or away from it, changing the intensity and duration of sunlight they receive."),
    ("What is photosynthesis?", "Photosynthesis is the process by which plants, algae, and some bacteria convert sunlight, carbon dioxide, and water into glucose and oxygen. It is the primary source of energy and oxygen in most ecosystems."),
    ("How does the moon affect tides?", "The moon's gravity pulls on Earth's oceans, creating a bulge of water on the side facing the moon and another on the opposite side. As Earth rotates, different locations pass through these bulges, producing high and low tides roughly twice a day."),
    ("What is a light-year?", "A light-year is the distance light travels in one year in a vacuum — approximately 9.46 trillion kilometres (5.88 trillion miles). It is used to measure vast astronomical distances."),
    ("Why do leaves change colour in autumn?", "In autumn, shorter days signal trees to stop producing chlorophyll (the green pigment). As it breaks down, other pigments — yellows, oranges, and reds — become visible, giving leaves their autumn colours before they fall."),
    ("What is the greenhouse effect?", "The greenhouse effect is the process by which certain gases in the atmosphere (like CO₂ and methane) trap heat from the sun, warming Earth's surface. Without it, Earth would be far colder; too much of it, caused by human emissions, drives climate change."),
    ("How far away is the moon?", "The moon is on average about 384,400 kilometres (about 239,000 miles) from Earth. Its distance varies slightly because its orbit is elliptical."),
    ("What is an atom?", "An atom is the basic unit of matter. It consists of a nucleus containing protons and neutrons, surrounded by electrons orbiting in shells. The number of protons determines which element the atom is."),
    ("How does sound travel?", "Sound travels as a wave of pressure variations through a medium — usually air, but also water, solids, etc. Vibrating objects create these pressure waves, which propagate outward and are detected by our ears or instruments."),
    ("What is the Big Bang?", "The Big Bang is the prevailing cosmological model for the origin of the universe. About 13.8 billion years ago, the universe began as an extremely hot, dense point and has been expanding and cooling ever since."),
    ("Why is the ocean salty?", "The ocean is salty because rivers continuously wash dissolved minerals and salts from rocks into the sea. Water evaporates from the ocean but salt stays behind, so salinity has built up over billions of years. Underwater volcanic vents also contribute minerals."),
    ("What is the difference between a virus and a bacterium?", "Bacteria are single-celled living organisms that can reproduce on their own. Viruses are much smaller and are not considered truly alive — they consist of genetic material (DNA or RNA) in a protein coat and can only reproduce by hijacking host cells."),
    ("How does the human brain work?", "The brain is a complex organ containing roughly 86 billion neurons connected by trillions of synapses. It processes sensory information, controls movement, regulates body functions, and generates thoughts, emotions, and memories through electrical and chemical signals."),
    ("What is climate change?", "Climate change refers to long-term shifts in global temperatures and weather patterns. While some change is natural, since the mid-20th century human activities — primarily burning fossil fuels — have been the main driver, increasing greenhouse gas concentrations and warming the planet."),
]

# History & people
pairs += [
    ("Who was JFK?", "John F. Kennedy (1917–1963) was the 35th President of the United States. He served from January 1961 until his assassination in Dallas, Texas, on November 22, 1963. He is remembered for the Cuban Missile Crisis, the early space programme, and his charismatic leadership during the Cold War."),
    ("Who was Cleopatra?", "Cleopatra VII (69–30 BC) was the last active ruler of the Ptolemaic Kingdom of Egypt. Known for her intelligence, political acumen, and relationships with Julius Caesar and Mark Antony, she remains one of history's most famous figures."),
    ("When did World War II end?", "World War II ended in 1945. Germany surrendered on May 8 (V-E Day), and Japan surrendered on September 2 (V-J Day) following the atomic bombings of Hiroshima and Nagasaki and the Soviet declaration of war against Japan."),
    ("What caused World War I?", "World War I (1914–1918) was triggered by the assassination of Archduke Franz Ferdinand of Austria-Hungary in Sarajevo on June 28, 1914. Deeper causes included a complex web of alliances, imperial rivalries, militarism, and nationalist tensions across Europe."),
    ("Who was Napoleon Bonaparte?", "Napoleon Bonaparte (1769–1821) was a French military general who rose to become Emperor of the French. He conquered much of Europe before his defeat at Waterloo in 1815. He is known for his military genius, the Napoleonic Code, and reshaping the political map of Europe."),
    ("What was the Renaissance?", "The Renaissance (roughly 14th–17th centuries) was a cultural and intellectual movement that began in Italy and spread across Europe. It marked a revival of interest in classical Greek and Roman ideas, and produced extraordinary achievements in art, literature, science, and philosophy."),
    ("Who invented the telephone?", "Alexander Graham Bell is widely credited with inventing the telephone and received the first patent for it in 1876. However, Elisha Gray filed a similar patent on the same day, and the Italian inventor Antonio Meucci had developed an earlier voice communication device."),
    ("Who was Mahatma Gandhi?", "Mahatma Gandhi (1869–1948) was an Indian lawyer and activist who led the nonviolent independence movement against British colonial rule in India. His philosophy of civil disobedience and peaceful protest inspired civil rights movements around the world."),
    ("What was the Cold War?", "The Cold War (1947–1991) was a period of geopolitical tension between the United States and the Soviet Union and their respective allies. It involved arms races, proxy wars, ideological competition, and events like the Berlin Wall and the Cuban Missile Crisis, but never escalated into direct large-scale warfare between the superpowers."),
    ("Who was Nikola Tesla?", "Nikola Tesla (1856–1943) was a Serbian-American inventor and electrical engineer best known for developing alternating current (AC) electrical systems. He also worked on radio, the Tesla coil, and wireless power transmission, and had a famous rivalry with Thomas Edison."),
    ("What was the Black Death?", "The Black Death was a devastating pandemic of bubonic plague that swept through Europe and Asia in the mid-14th century (1347–1351). It killed an estimated 30–60% of Europe's population and had profound effects on society, religion, and the economy."),
    ("Who was Abraham Lincoln?", "Abraham Lincoln (1809–1865) was the 16th President of the United States. He led the country through the Civil War, abolished slavery with the Emancipation Proclamation, and was assassinated by John Wilkes Booth in April 1865, just days after the war ended."),
    ("When did humans first land on the moon?", "Apollo 11 successfully landed humans on the moon on July 20, 1969. Neil Armstrong became the first person to walk on the lunar surface, followed by Buzz Aldrin, while Michael Collins orbited above."),
    ("Who was Genghis Khan?", "Genghis Khan (c. 1162–1227) was the founder and first Great Khan of the Mongol Empire, which became the largest contiguous land empire in history. He united Mongol tribes and conquered vast territories across Asia and Eastern Europe through military innovation and ruthless warfare."),
    ("What was the French Revolution?", "The French Revolution (1789–1799) was a period of radical political and social transformation in France. It abolished the monarchy and feudal system, declared the rights of man and citizen, and ended with Napoleon Bonaparte's rise to power. It profoundly influenced modern democracy and nationalism."),
    ("Who was Albert Einstein?", "Albert Einstein (1879–1955) was a German-born theoretical physicist who developed the special and general theories of relativity. He won the 1921 Nobel Prize in Physics for his explanation of the photoelectric effect and is widely regarded as one of the greatest scientists in history."),
    ("What was the Roman Empire?", "The Roman Empire was one of the largest empires in ancient history, at its peak controlling territory from Britain to Mesopotamia. It lasted from 27 BC to 476 AD (Western Roman Empire) and shaped Western civilisation through its law, language, architecture, and culture."),
    ("Who was Nelson Mandela?", "Nelson Mandela (1918–2013) was a South African anti-apartheid activist and statesman. He spent 27 years in prison for his opposition to apartheid, and after his release negotiated the end of apartheid. He became South Africa's first democratically elected president in 1994 and was awarded the Nobel Peace Prize."),
    ("What happened at Hiroshima?", "On August 6, 1945, the United States dropped an atomic bomb on the Japanese city of Hiroshima, killing an estimated 70,000–80,000 people immediately and many more from radiation exposure afterward. It was the first wartime use of a nuclear weapon, followed by a second bomb on Nagasaki three days later."),
    ("Who was Charles Darwin?", "Charles Darwin (1809–1882) was a British naturalist who developed the theory of evolution by natural selection, most famously presented in his 1859 work 'On the Origin of Species'. His work revolutionised biology and our understanding of life on Earth."),
    ("What was apartheid?", "Apartheid was a system of institutionalised racial segregation and discrimination enforced in South Africa from 1948 to the early 1990s. It legally separated people by race, denying non-white citizens basic rights. International pressure and internal resistance eventually led to its dismantlement and the first democratic elections in 1994."),
    ("Who built the pyramids?", "The ancient Egyptians built the pyramids as tombs for their pharaohs. The Great Pyramid of Giza, built for Pharaoh Khufu around 2560 BC, is the largest. Modern archaeology indicates they were built by skilled paid labourers, not slaves as was once popularly believed."),
    ("Who was Winston Churchill?", "Winston Churchill (1874–1965) was a British statesman who served as Prime Minister of the United Kingdom twice (1940–1945 and 1951–1955). He is best known for his leadership during World War II, rallying Britain against Nazi Germany with powerful speeches and strategic resolve."),
    ("What caused the Great Depression?", "The Great Depression (1929–1939) was triggered by the Wall Street Crash of October 1929 and worsened by bank failures, falling agricultural prices, restrictive trade policies, and the collapse of international lending. It caused mass unemployment and severe economic hardship worldwide."),
    ("Who was Marie Curie?", "Marie Curie (1867–1934) was a Polish-French physicist and chemist who pioneered research on radioactivity. She was the first woman to win a Nobel Prize and the only person to win Nobel Prizes in two different sciences (Physics in 1903, Chemistry in 1911)."),
]

# Geography
pairs += [
    ("What is the longest river in the world?", "The Nile in Africa is traditionally considered the world's longest river at about 6,650 km, though some measurements place the Amazon River in South America slightly longer. The debate depends on how the source of each river is defined."),
    ("What is the capital of Australia?", "The capital of Australia is Canberra. It was purpose-built as a compromise between the rival cities of Sydney and Melbourne, and became the capital in 1913."),
    ("What is the largest country by area?", "Russia is the largest country in the world by land area, covering about 17.1 million square kilometres — roughly 11% of Earth's total land area."),
    ("How many continents are there?", "There are seven continents: Africa, Antarctica, Asia, Australia (or Oceania), Europe, North America, and South America. Some models, particularly in parts of Europe and Latin America, use a six-continent model that combines Europe and Asia into Eurasia."),
    ("What is the highest mountain in the world?", "Mount Everest, in the Himalayas on the border of Nepal and Tibet, is the highest mountain in the world at 8,848.86 metres (29,031.7 feet) above sea level."),
    ("What is the smallest country in the world?", "Vatican City is the smallest country in the world by both area (about 0.44 km²) and population (around 800 people). It is an independent city-state within Rome, serving as the headquarters of the Roman Catholic Church."),
    ("Where is the Sahara Desert?", "The Sahara Desert is located in North Africa and is the world's largest hot desert, covering approximately 9.2 million square kilometres. It stretches across 11 countries, including Algeria, Libya, Egypt, Mali, Niger, and Chad."),
    ("What is the deepest ocean?", "The Pacific Ocean is the deepest, containing the Mariana Trench, which reaches a maximum depth of about 11,034 metres (36,201 feet) at a point called Challenger Deep — the deepest known point on Earth."),
    ("What is the population of the world?", "As of 2024, the world population is approximately 8.1 billion people. It reached 8 billion in November 2022 and continues to grow, though the rate of growth is slowing."),
    ("What language is spoken in Brazil?", "Portuguese is the official and most widely spoken language of Brazil. Brazil is the largest Portuguese-speaking country in the world, a result of Portuguese colonisation beginning in the 16th century."),
    ("What is the Amazon rainforest?", "The Amazon rainforest is the world's largest tropical rainforest, covering about 5.5 million km² across nine South American countries, primarily Brazil. It is home to an extraordinary diversity of plant and animal species and plays a crucial role in regulating Earth's climate."),
    ("What is the capital of Canada?", "The capital of Canada is Ottawa, located in the province of Ontario. Despite being less well-known internationally than Toronto or Vancouver, Ottawa has been Canada's capital since 1857."),
    ("Which is the largest ocean?", "The Pacific Ocean is the largest ocean, covering about 165 million square kilometres — more than all of Earth's landmasses combined. It stretches from the Arctic to the Antarctic and from Asia to the Americas."),
    ("Where is Patagonia?", "Patagonia is a large region at the southern end of South America, shared between Argentina and Chile. It is known for its dramatic landscapes, including glaciers, mountains, steppes, and fjords."),
    ("What is the population of China?", "China has a population of approximately 1.4 billion people, making it one of the two most populous countries in the world alongside India, which recently surpassed China's population."),
]

# Everyday life & advice
pairs += [
    ("How do I get better at sleeping?", "Improving sleep often comes down to consistent habits: go to bed and wake up at the same time every day, keep your bedroom cool and dark, avoid screens for an hour before bed, limit caffeine after noon, and avoid alcohol close to bedtime. Regular exercise also helps, though not right before sleep."),
    ("What should I eat to stay healthy?", "A balanced diet generally includes plenty of vegetables and fruit, whole grains, lean proteins (like fish, legumes, and poultry), and healthy fats (like those from nuts and olive oil). Limiting processed foods, added sugars, and excessive salt is also important. Most guidelines recommend variety and moderation rather than strict rules."),
    ("How much water should I drink per day?", "A common guideline is about 8 cups (2 litres) of water per day for adults, but the actual amount depends on your body size, activity level, and climate. Many people meet their fluid needs through water and other beverages combined with water-rich foods like fruit and vegetables."),
    ("How do I manage stress?", "Effective stress management strategies include regular physical exercise, mindfulness or meditation, adequate sleep, and social connection. Breaking large problems into smaller steps, setting boundaries, and talking to someone you trust also help. If stress is chronic or overwhelming, speaking with a therapist or doctor is worthwhile."),
    ("What is the best way to learn a new language?", "Consistent daily practice is key. Combine multiple methods: formal lessons or apps for structure, immersion through native content (films, books, podcasts), speaking practice with native speakers or language partners, and active use of new vocabulary. Aiming for daily exposure, even in short sessions, beats long occasional study sessions."),
    ("How do I start exercising?", "Start small and be consistent. Even 20–30 minutes of brisk walking most days is a great foundation. Gradually add variety — strength training, cycling, swimming, or whatever you enjoy. Setting specific goals, finding activities you like, and exercising with a friend all improve adherence. The best exercise is one you'll actually do."),
    ("How do I save money?", "Track your spending to understand where money goes, then set a budget. Prioritise building an emergency fund first. Automate savings by setting up direct transfers to a savings account on payday. Cut discretionary spending on things that don't bring lasting satisfaction, and avoid impulse purchases by waiting 24 hours before buying non-essentials."),
    ("What's a good morning routine?", "A good morning routine often includes waking at a consistent time, avoiding your phone for the first 15–30 minutes, some form of movement (even a short walk), a nutritious breakfast, and a few minutes of planning your day. The key is keeping it realistic and consistent rather than elaborate."),
    ("How do I improve my focus?", "To improve focus: work in blocks (e.g. 25 minutes on, 5 off), remove distractions by silencing notifications, keep a clear workspace, and have a specific task in mind before starting. Getting enough sleep, regular exercise, and limiting caffeine also significantly impact concentration."),
    ("How do I deal with a difficult coworker?", "Try to understand their perspective first — difficult behaviour often has causes unrelated to you. Address specific issues directly and calmly, using 'I' statements rather than accusations. If that fails, document incidents and involve your manager or HR. Maintaining professional boundaries and not letting the situation affect your work quality protects you."),
    ("What is a good way to apologise?", "A sincere apology should acknowledge what you did wrong, express genuine regret, take responsibility without excuses, and — if possible — commit to doing better. Avoid 'I'm sorry you feel that way', which shifts blame. Sometimes giving the other person space before apologising helps the message land better."),
    ("How do I stop procrastinating?", "Break tasks into the smallest possible first step — often starting is the hardest part. Set specific times to work rather than vague intentions. Remove temptations (phone, social media) during work periods. Recognise that you rarely need to feel motivated to start; motivation often follows action rather than preceding it."),
    ("What's the best way to make new friends as an adult?", "Put yourself in recurring environments where you meet the same people — classes, clubs, community groups, or regular social events. Follow up after a good conversation. Suggest specific plans rather than vague 'we should hang out'. Friendships form through repeated contact and gradually increasing openness, so consistency matters more than any single interaction."),
    ("How do I read more books?", "Replace a low-value habit (scrolling before bed, commuting with nothing) with reading. Always have your current book accessible. Don't feel obligated to finish books you're not enjoying — abandoning a bad book frees you for a better one. Joining a book club or tracking your reading can also maintain motivation."),
    ("How do I negotiate a raise?", "Research market rates for your role and document your specific contributions and achievements. Request a dedicated meeting rather than raising it informally. State your request confidently with a specific number, backed by your evidence. Be prepared for negotiation — consider the full package including benefits, flexibility, and growth opportunities, not just salary."),
    ("How do I get out of a bad mood?", "Short-term: physical exercise is one of the most reliable mood lifters, even a brief walk. Talking to a friend, getting sunlight, listening to music, or doing something creative can help. For recurring low moods, addressing underlying causes — sleep, stress, social connection — is more effective than quick fixes."),
    ("What is a good way to take notes?", "The best note-taking method depends on the context. For lectures, the Cornell method (main notes, cues, summary) works well. For reading, brief summaries in your own words beat verbatim copying. Digital tools like Notion or Obsidian are useful for organisation. Reviewing notes soon after taking them dramatically improves retention."),
    ("How do I become more confident?", "Confidence is largely built through action — taking small risks, doing things outside your comfort zone, and accumulating evidence that you can handle challenges. Prepare thoroughly for situations that make you anxious. Focus on contribution rather than impression. Avoid comparing your internal experience to others' external presentation."),
    ("How do I write a good CV?", "Keep it concise (one or two pages), tailor it to each role, and lead with impact. Use action verbs and include specific achievements with numbers where possible ('increased sales by 20%' beats 'responsible for sales'). Ensure there are no typos, use a clean format, and prioritise recent and relevant experience."),
    ("What is a healthy work-life balance?", "Healthy work-life balance means having time for work, personal relationships, health, and rest without chronic overload in any area. It varies by individual, but generally includes defined work hours, regular time off, and activities outside work that you value. It often requires actively setting boundaries rather than waiting for balance to happen naturally."),
]

# Food & cooking
pairs += [
    ("How do I make pasta from scratch?", "Mix 100g of 00 flour (or plain flour) with 1 egg per person. Knead for 8–10 minutes until smooth, wrap and rest for 30 minutes. Roll out thinly with a rolling pin or pasta machine, then cut into your desired shape. Fresh pasta cooks in just 2–3 minutes in boiling salted water."),
    ("What is the difference between baking soda and baking powder?", "Baking soda (bicarbonate of soda) is a base that needs an acid (like buttermilk or lemon juice) to produce CO₂ and cause rising. Baking powder already contains both a base and an acid and only needs moisture and heat, so it works in recipes without acidic ingredients."),
    ("How do I cook rice perfectly?", "Rinse the rice until the water runs clear, then use a 1:1.5 ratio (1 cup rice to 1.5 cups water). Bring to a boil, add the rice, reduce heat to very low, cover tightly, and simmer for 15–18 minutes. Don't lift the lid. Remove from heat and let it steam, covered, for 10 more minutes before fluffing with a fork."),
    ("What is umami?", "Umami is the fifth basic taste, alongside sweet, salty, sour, and bitter. It is described as a savoury, meaty, or brothy flavour and is caused by naturally occurring compounds like glutamate. Foods rich in umami include parmesan, miso, mushrooms, tomatoes, soy sauce, and meat."),
    ("How do I make bread without a bread machine?", "Combine flour, salt, yeast, and water; knead for 10 minutes until smooth and elastic. Let it rise in a warm place until doubled (about 1 hour), then shape, place in a tin, and let it rise again (30–45 minutes). Bake in a hot oven (220°C/425°F) for 25–30 minutes until golden and hollow-sounding when tapped underneath."),
    ("What makes food spicy?", "The spiciness in chillies comes from capsaicin, a compound that binds to pain receptors (TRPV1) in the mouth and throat, creating the sensation of heat. The Scoville scale measures a chilli's hotness. Milk and other dairy products help relieve the burn because casein protein binds to capsaicin, unlike water which just spreads it."),
    ("What is the difference between white and brown rice?", "Brown rice is a whole grain with only the outer husk removed, retaining the bran and germ layers. This makes it higher in fibre, vitamins, and minerals but also harder and chewier with a longer cooking time. White rice has had the bran and germ removed, making it more refined but lower in nutrients."),
    ("How do I caramelise onions?", "Slice onions thinly, heat butter or oil in a pan over medium-low heat, add the onions with a pinch of salt, and cook slowly — stirring occasionally — for 30–45 minutes. Patience is essential; high heat browns them but doesn't truly caramelise them. They're ready when deeply golden and very soft."),
    ("What is the Maillard reaction?", "The Maillard reaction is a chemical reaction between amino acids and reducing sugars that occurs when food is heated above about 140°C. It creates hundreds of flavour and aroma compounds and is responsible for the browning of bread, the crust on seared meat, the colour of roasted coffee, and many other delicious flavours."),
    ("How do I store fresh herbs?", "Tender herbs like basil, parsley, and coriander keep best stored like flowers — stems in a glass of water at room temperature (basil) or in the fridge (parsley, coriander). Hardier herbs like thyme and rosemary can be wrapped loosely in damp paper towel and stored in the fridge. Most fresh herbs can also be frozen after chopping."),
]

# Culture, arts & literature
pairs += [
    ("Who wrote Romeo and Juliet?", "Romeo and Juliet was written by William Shakespeare, probably around 1594–1596. It is a tragedy about two young lovers from feuding families in Verona whose deaths ultimately reconcile their families. It remains one of the most performed plays in the world."),
    ("What is the Mona Lisa?", "The Mona Lisa is a portrait painted by Leonardo da Vinci between approximately 1503 and 1519. It depicts a woman — widely believed to be Lisa Gherardini — and is famous for her enigmatic smile. It hangs in the Louvre Museum in Paris and is perhaps the most recognised painting in the world."),
    ("Who wrote '1984'?", "1984 was written by the British author George Orwell and published in 1949. It is a dystopian novel set in a totalitarian society ruled by 'Big Brother', and explores themes of surveillance, propaganda, and the destruction of truth. Terms like 'doublethink', 'thoughtcrime', and 'Orwellian' originate from the book."),
    ("What is jazz music?", "Jazz is a music genre that originated in New Orleans, Louisiana, in the late 19th and early 20th centuries, drawing on African American musical traditions including blues and ragtime. It is characterised by improvisation, syncopated rhythms, and a strong interplay between performers. Key figures include Louis Armstrong, Miles Davis, and John Coltrane."),
    ("Who is Beethoven?", "Ludwig van Beethoven (1770–1827) was a German composer and pianist, widely regarded as one of the greatest composers in Western musical history. He created works including nine symphonies, piano sonatas, and string quartets, remarkably continuing to compose after going almost completely deaf."),
    ("What is impressionism in painting?", "Impressionism was an art movement that originated in France in the 1860s–1870s, characterised by loose brushwork, an interest in capturing light and atmosphere rather than precise detail, and painting en plein air (outdoors). Key impressionist painters include Claude Monet, Pierre-Auguste Renoir, and Edgar Degas."),
    ("Who wrote 'Pride and Prejudice'?", "Pride and Prejudice was written by Jane Austen and published in 1813. The novel explores themes of marriage, social class, and personal growth through the story of Elizabeth Bennet and Mr. Darcy. It is one of the most beloved novels in English literature."),
    ("What is hip-hop?", "Hip-hop is a cultural movement and music genre that emerged in the Bronx, New York City, in the early 1970s, primarily within African American and Latino communities. It has four main elements: rapping (MCing), DJing, breakdancing, and graffiti writing. It has since become one of the dominant global music genres."),
    ("Who painted the Sistine Chapel ceiling?", "The Sistine Chapel ceiling was painted by Michelangelo between 1508 and 1512, commissioned by Pope Julius II. The most famous section depicts 'The Creation of Adam'. It is widely considered one of the greatest works of art in history."),
    ("What is the difference between fiction and non-fiction?", "Fiction is writing that is invented or imagined — novels, short stories, and plays that describe people and events that are not real (though they may be inspired by reality). Non-fiction is writing based on real facts, events, and people — including biographies, journalism, history, and science writing."),
]

# Technology & the internet
pairs += [
    ("What is artificial intelligence?", "Artificial intelligence (AI) refers to computer systems designed to perform tasks that typically require human intelligence — such as understanding language, recognising images, making decisions, and learning from experience. Modern AI is dominated by machine learning, where systems learn patterns from large datasets rather than being explicitly programmed with rules."),
    ("What is the internet?", "The internet is a global network of interconnected computers and devices that communicate using standardised protocols (primarily TCP/IP). It supports services like the World Wide Web, email, streaming, and messaging. It originated from ARPANET, a US military research network developed in the 1960s."),
    ("What is a smartphone?", "A smartphone is a mobile phone with advanced computing capabilities, essentially a pocket-sized computer. Beyond making calls and sending texts, smartphones run apps, access the internet, take photos, provide GPS navigation, and perform many other functions. Apple's iPhone (2007) and Android-based devices transformed the market."),
    ("What is blockchain?", "A blockchain is a distributed digital ledger that records transactions across many computers in a way that makes them very difficult to alter retroactively. Each 'block' contains transaction data and a link to the previous block, forming a chain. It underpins cryptocurrencies like Bitcoin but has broader applications in supply chain, contracts, and record-keeping."),
    ("What is cloud computing?", "Cloud computing means accessing computing resources — servers, storage, software, databases — over the internet rather than running them locally. Services like Google Drive, Dropbox, and Netflix run in 'the cloud'. It lets individuals and businesses scale resources on demand without owning physical infrastructure."),
    ("What is machine learning?", "Machine learning is a branch of artificial intelligence where systems learn from data to improve their performance on a task without being explicitly programmed for each scenario. By exposing a model to many examples, it learns patterns it can then apply to new data. It underlies recommendation systems, image recognition, language models, and much more."),
    ("What is social media?", "Social media are online platforms that allow users to create and share content and participate in social networking. Examples include Facebook, Instagram, Twitter/X, TikTok, and LinkedIn. They have transformed communication, news distribution, marketing, and social interaction, while also raising concerns about privacy, mental health, and misinformation."),
    ("What is a VPN?", "A VPN (Virtual Private Network) creates an encrypted tunnel between your device and a server, masking your IP address and securing your internet traffic. It's used to protect privacy on public Wi-Fi, bypass geographical restrictions on content, or access remote corporate networks securely."),
    ("What is cybersecurity?", "Cybersecurity is the practice of protecting computers, networks, programs, and data from digital attacks, damage, or unauthorised access. It involves measures like firewalls, encryption, strong passwords, software updates, and training users to recognise threats like phishing. It has become increasingly critical as more aspects of life and infrastructure depend on digital systems."),
    ("What is the difference between the internet and the World Wide Web?", "The internet is the global network of computers and the infrastructure connecting them. The World Wide Web is a service that runs on the internet — the system of websites, pages, and links you access through a browser using HTTP. The web is one of many services the internet supports, alongside email, messaging, and file transfer."),
]

# Economics & society
pairs += [
    ("What is inflation?", "Inflation is the rate at which the general level of prices for goods and services rises over time, reducing purchasing power. Moderate inflation is normal in healthy economies; very high inflation (hyperinflation) can destabilise an economy. Central banks manage inflation primarily through interest rates."),
    ("What is GDP?", "GDP (Gross Domestic Product) is the total monetary value of all goods and services produced within a country in a specific period. It is the most widely used measure of the size of an economy. GDP per capita (divided by population) gives a rough measure of average living standards."),
    ("What is democracy?", "Democracy is a system of government in which power is vested in the people, who exercise it directly or through elected representatives. Core principles typically include free and fair elections, protection of individual rights, rule of law, and freedom of expression. There are many variations, from direct democracy to representative parliamentary systems."),
    ("What is capitalism?", "Capitalism is an economic system in which the means of production are privately owned and operated for profit, with prices, production, and distribution determined mainly by competition in free markets. Most modern economies are mixed — combining market mechanisms with government regulation and social programmes."),
    ("What is the United Nations?", "The United Nations (UN) is an international organisation founded in 1945 with the goal of maintaining international peace and security, promoting human rights, and fostering international cooperation. It currently has 193 member states. Its main bodies include the General Assembly, the Security Council, and various specialised agencies."),
    ("What is globalisation?", "Globalisation refers to the increasing interconnection of economies, cultures, and societies around the world through trade, communication, migration, and technology. It has accelerated since the late 20th century, bringing economic growth and cultural exchange but also concerns about inequality, job displacement, and cultural homogenisation."),
    ("What is the stock market?", "The stock market is a marketplace where shares of publicly listed companies are bought and sold. Investors buy shares hoping the company's value will grow; companies sell shares to raise capital. Stock exchanges like the NYSE and Nasdaq provide the infrastructure. Stock prices reflect the collective assessment of a company's current and future value."),
    ("What is a recession?", "A recession is a period of significant economic decline, typically defined as two or more consecutive quarters of negative GDP growth. Recessions are characterised by rising unemployment, reduced consumer spending, and lower business investment. Governments and central banks typically respond with fiscal stimulus and lower interest rates."),
    ("What is the difference between a republic and a democracy?", "A democracy is a system where governing power derives from the people. A republic is a system where the state is considered a public matter and officials are elected to represent the people rather than inheriting power. Most modern democracies are also republics. The key distinction is that republics have elected representatives rather than hereditary rulers, while democracy emphasises popular sovereignty."),
    ("What is the EU?", "The European Union (EU) is a political and economic union of 27 European member states. It operates a single market allowing free movement of goods, services, capital, and people. It has its own parliament, court, and — for 20 members — a shared currency (the euro). It was formed to promote peace, cooperation, and economic integration after the Second World War."),
]

# Maths & logic
pairs += [
    ("What is the Pythagorean theorem?", "The Pythagorean theorem states that in a right-angled triangle, the square of the length of the hypotenuse (the side opposite the right angle) equals the sum of the squares of the other two sides: a² + b² = c². It is one of the most fundamental results in geometry."),
    ("What is a prime number?", "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. Examples include 2, 3, 5, 7, 11, and 13. Every number greater than 1 can be expressed as a unique product of prime numbers (the fundamental theorem of arithmetic)."),
    ("What is pi?", "Pi (π) is the mathematical constant representing the ratio of a circle's circumference to its diameter. It is approximately 3.14159 and is an irrational number — its decimal expansion never ends or repeats. Pi appears throughout mathematics, physics, and engineering."),
    ("What is the Fibonacci sequence?", "The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ... It appears surprisingly often in nature — in the arrangement of leaves, the spirals of shells, and the branching of trees — and has connections to the golden ratio."),
    ("What does infinity mean in maths?", "In mathematics, infinity (∞) is not a number but a concept describing something without bound or end. There are different 'sizes' of infinity — for example, the mathematician Georg Cantor proved that the infinity of real numbers is larger than the infinity of natural numbers, a deeply counterintuitive result."),
    ("What is a percentage?", "A percentage is a way of expressing a number as a fraction of 100. For example, 25% means 25 out of every 100, or 0.25 as a decimal. To calculate a percentage of a number, multiply the number by the percentage divided by 100. For example, 25% of 80 = (25/100) × 80 = 20."),
    ("What is probability?", "Probability is a measure of how likely an event is to occur, expressed as a number between 0 (impossible) and 1 (certain). A fair coin has a 0.5 (50%) probability of landing heads. Probability theory underpins statistics, gambling, insurance, machine learning, and many scientific fields."),
    ("What is calculus?", "Calculus is a branch of mathematics developed by Newton and Leibniz in the 17th century. It has two main parts: differential calculus (concerned with rates of change and slopes of curves) and integral calculus (concerned with accumulation of quantities and areas under curves). It is essential in physics, engineering, economics, and many other fields."),
    ("What is algebra?", "Algebra is a branch of mathematics dealing with symbols (often letters like x and y) that represent numbers or quantities in equations and formulas. It generalises arithmetic by allowing us to express and solve relationships between unknown values. It forms the foundation for most advanced mathematics."),
    ("What is the difference between mean, median, and mode?", "Mean is the average — add all values and divide by the count. Median is the middle value when data is sorted; it is less affected by extreme values. Mode is the value that appears most often. For example, in the set {2, 3, 3, 5, 10}: mean = 4.6, median = 3, mode = 3."),
]

# Health & medicine
pairs += [
    ("What is a vaccine?", "A vaccine is a biological preparation that trains the immune system to recognise and fight a specific pathogen. It typically contains a weakened, killed, or partial version of the pathogen (or, in the case of mRNA vaccines, instructions to produce a recognisable protein). Vaccination has eradicated smallpox and dramatically reduced diseases like polio, measles, and tetanus."),
    ("What is diabetes?", "Diabetes is a chronic condition affecting how the body processes blood sugar (glucose). Type 1 diabetes is an autoimmune condition where the pancreas produces little or no insulin. Type 2 is the more common form, where the body doesn't use insulin effectively, often linked to lifestyle factors. Both require ongoing management to prevent complications."),
    ("What is blood pressure?", "Blood pressure is the force of blood against artery walls as the heart pumps. It is measured as two numbers: systolic (pressure during heartbeats) over diastolic (pressure between beats), in mmHg. A normal reading is around 120/80. High blood pressure (hypertension) is a major risk factor for heart disease and stroke."),
    ("Why is sleep important?", "Sleep is essential for physical and mental health. During sleep, the body repairs tissue, consolidates memories, regulates hormones, and clears waste products from the brain. Chronic sleep deprivation is linked to increased risk of obesity, diabetes, cardiovascular disease, impaired immune function, and mental health problems."),
    ("What is depression?", "Depression is a common mental health disorder characterised by persistent feelings of sadness, hopelessness, and loss of interest, along with physical symptoms like fatigue, sleep disruption, and changes in appetite. It has biological, psychological, and social causes and is effectively treated with therapy, medication, or a combination of both."),
    ("What is BMI?", "BMI (Body Mass Index) is a measure calculated by dividing weight (in kg) by height squared (in m²). It is used as a rough screening tool for weight categories: underweight (<18.5), normal (18.5–24.9), overweight (25–29.9), and obese (≥30). It has limitations — it doesn't account for muscle mass, bone density, or fat distribution."),
    ("How does exercise benefit health?", "Regular exercise improves cardiovascular health, strengthens muscles and bones, aids weight management, improves sleep quality, and reduces the risk of type 2 diabetes, certain cancers, and cardiovascular disease. It also has powerful mental health benefits, reducing symptoms of depression and anxiety and improving mood and cognitive function."),
    ("What is cholesterol?", "Cholesterol is a fatty substance found in blood that is essential for building cells and producing hormones. Problems arise when LDL ('bad') cholesterol builds up in artery walls, increasing the risk of heart disease and stroke. HDL ('good') cholesterol helps remove LDL from the bloodstream. Diet, exercise, and sometimes medication manage cholesterol levels."),
    ("What is antibiotic resistance?", "Antibiotic resistance occurs when bacteria evolve mechanisms to survive exposure to antibiotics, making infections harder or impossible to treat. It is driven by overuse and misuse of antibiotics in humans and livestock. The World Health Organisation considers it one of the greatest threats to global health, as common infections could become untreatable."),
    ("What is the difference between a cold and the flu?", "Both are respiratory illnesses, but influenza (flu) is generally more severe. The flu usually comes on suddenly with fever, body aches, fatigue, and headache. Colds typically develop gradually with runny nose, sneezing, and mild sore throat. Flu can lead to serious complications including pneumonia, while colds are usually self-limiting."),
]

# Sports & leisure
pairs += [
    ("How long is a marathon?", "A marathon is 42.195 kilometres (26.219 miles) long. The distance was standardised at the 1908 London Olympics to go from Windsor Castle to the Olympic stadium. The world record is just over 2 hours (set by Eliud Kipchoge)."),
    ("What is the offside rule in football (soccer)?", "A player is offside if they are in the opposing half and closer to the goal line than both the ball and the second-to-last defender (usually the last outfield player) at the moment the ball is played to them. Being offside is not itself an offence — it only becomes one if the player becomes actively involved in play."),
    ("How does the Tour de France work?", "The Tour de France is a 21-stage road cycling race held annually in July, covering about 3,400 km mainly through France. Riders accumulate time over all stages; the rider with the lowest total time wins the yellow jersey (overall leader). Other jerseys reward best sprinter (green), best climber (polka dot), and best young rider (white)."),
    ("How many players are on a basketball team?", "A basketball team has 5 players on the court at a time. A typical team roster has 12–15 players, with substitutions allowed throughout the game. Positions are generally guard, forward, and centre, though modern basketball often uses flexible position-less lineups."),
    ("What is a Grand Slam in tennis?", "A Grand Slam refers to the four most prestigious tennis tournaments: the Australian Open, the French Open (Roland Garros), Wimbledon, and the US Open. Winning all four in the same calendar year is called winning 'the Grand Slam', a feat achieved by very few players in history."),
    ("What are the rules of chess?", "Chess is a strategy game for two players on an 8×8 board. Each player starts with 16 pieces: a king, queen, two rooks, two bishops, two knights, and eight pawns. Each piece type moves differently. The goal is to checkmate the opponent's king — put it under attack with no legal escape. The game ends by checkmate, resignation, or draw."),
    ("What is the difference between rugby union and rugby league?", "Both are versions of rugby but have key differences. Rugby union has 15 players per side and a complex breakdown/scrum system. Rugby league has 13 players, simpler rules, and a tackle count (6 tackles before possession changes). Union is more popular globally; league is particularly strong in northern England and Australia."),
    ("How does Formula 1 work?", "Formula 1 is the highest class of single-seater motor racing. Teams design and build cars under strict technical regulations, and drivers compete in a season of around 23 races (Grands Prix) around the world. Points are awarded based on finishing position; the driver and constructor with the most points at the season's end win the championships."),
    ("What is the Olympic Games?", "The Olympic Games are a major international multi-sport event held every four years. The Summer Olympics and Winter Olympics alternate every two years. The modern Games were revived in 1896 in Athens, inspired by the ancient Greek Games. Athletes from over 200 countries compete, making it the world's largest sporting event."),
    ("How does scoring work in cricket?", "In cricket, runs are scored when batsmen run between the wickets after hitting the ball, or when the ball reaches the boundary (4 runs) or clears it without bouncing (6 runs). The batting team aims to score as many runs as possible before losing 10 wickets. The team with the most runs after the agreed number of innings wins."),
]

# Miscellaneous interesting questions
pairs += [
    ("Why do we yawn?", "The exact function of yawning is still not fully understood. Leading theories include that it helps cool the brain, signals tiredness, or facilitates a transition between states of alertness. Yawning is also contagious in humans and some other animals, possibly linked to empathy and social bonding."),
    ("Why do cats purr?", "Cats purr by rapid movement of the larynx muscles, causing air to vibrate during breathing. While purring most often signals contentment, cats also purr when stressed, injured, or giving birth — suggesting it may also be a self-soothing mechanism. Interestingly, the frequency (25–150 Hz) may have healing properties for bones and muscles."),
    ("Why do we have fingerprints?", "Fingerprints are formed during foetal development and are thought to improve grip by channelling moisture away from the fingertips and increasing friction, similar to the way tyre treads work. Each person's fingerprints are unique due to random variation in foetal development, which is why they are used for identification."),
    ("How do aeroplanes stay in the air?", "Aeroplanes generate lift by moving their wings rapidly through the air. The wing's shape and angle of attack cause air to move faster over the top surface than underneath, creating lower pressure above and higher pressure below, pushing the wing (and plane) upward. Engines provide thrust to maintain the speed needed for this lift."),
    ("Why does the moon appear larger near the horizon?", "The moon illusion — the moon appearing larger near the horizon than high in the sky — is a perceptual phenomenon, not a physical one. The moon is actually the same size and distance. The most accepted explanation involves the brain comparing the horizon moon to terrestrial objects, making it seem larger by contrast."),
    ("How do magnets work?", "Magnetism arises from the motion of electric charges, particularly electrons. In magnetic materials, electrons' intrinsic 'spin' creates tiny magnetic moments that align in the same direction in 'magnetic domains'. When most domains align, the material becomes a magnet. Opposite poles attract because their magnetic field lines connect in a complete circuit."),
    ("Why is glass transparent?", "Glass is transparent because its molecular structure — primarily silicon dioxide — doesn't absorb visible light. Photons of visible light pass through without being absorbed (unlike in opaque materials where photons are absorbed or scattered). The atoms in glass are also arranged randomly rather than in a crystal lattice, preventing light scattering."),
    ("How do we remember things?", "Memory formation involves three stages: encoding (taking in information), storage (retaining it), and retrieval (recalling it). The hippocampus in the brain is crucial for forming new memories, which are then consolidated during sleep. Repetition, emotional significance, and association with existing knowledge all strengthen memories."),
    ("Why do we get goosebumps?", "Goosebumps (piloerection) are caused by tiny muscles at the base of hair follicles contracting, causing hairs to stand up. It is an evolutionary holdover — in our hairier ancestors, this made them appear larger to predators and provided warmth by trapping air. Today it occurs during cold, fear, or strong emotional responses."),
    ("What is the placebo effect?", "The placebo effect is the measurable, real improvement in a patient's condition caused by belief in the treatment rather than the treatment itself. Placebos — typically inert substances — can reduce pain, anxiety, and other symptoms through expectation and conditioning. Understanding this effect is crucial in drug trials, which use placebo-controlled studies."),
    ("How do we know what dinosaurs looked like?", "We know about dinosaur anatomy primarily from fossils — preserved bones, teeth, and occasionally skin impressions and feather traces. Palaeontologists reconstruct body shape from skeletons, infer muscle mass from bone attachment points, and use close living relatives (birds and crocodilians) as reference for soft tissue. Colouration is increasingly inferred from fossilised pigment cells."),
    ("Why is the sea blue?", "The sea appears blue for two reasons: it absorbs red wavelengths of light more than blue, so returning light is blue-shifted; and it reflects the blue sky. In shallow, clear water the sea floor also affects colour — hence the vivid turquoise of shallow tropical seas where sand reflects light upward."),
    ("Can humans live on Mars?", "Living on Mars poses enormous challenges: the thin atmosphere (mostly CO₂) provides no breathable air and little protection from radiation, temperatures average −60°C, and there is no liquid surface water. In principle these could be overcome with technology — pressurised habitats, spacesuits, radiation shielding, resource extraction. No human has yet visited Mars; it remains a long-term aspiration."),
    ("What is the fastest animal on Earth?", "The peregrine falcon is the fastest animal, reaching speeds over 390 km/h (240 mph) in a hunting dive (stoop). On the ground, the cheetah is the fastest land animal at up to 120 km/h (75 mph) in short bursts. In water, the sailfish is among the fastest at around 110 km/h."),
    ("How many bones does a human have?", "An adult human body has 206 bones. Babies are born with around 270–300, but many fuse together during childhood and adolescence. The smallest bone is the stirrup (stapes) in the ear; the longest is the femur (thigh bone)."),
    ("What is déjà vu?", "Déjà vu is the strange feeling that a new experience has happened before. It is thought to occur when part of the brain processes a new experience through memory systems rather than perception systems, creating a false sense of familiarity. It is very common and usually harmless, occurring more frequently in younger people and those who are tired."),
    ("What is the meaning of life?", "That depends who you ask. Philosophers have offered many answers: Aristotle argued it is eudaimonia (flourishing through virtue and reason); existentialists like Sartre held that life has no inherent meaning and humans must create their own; many religious traditions point to service, devotion, or spiritual growth. Most people settle on answers involving connection, purpose, and contribution."),
]

# ---------------------------------------------------------------------------
# Expand to ~6000 by slightly paraphrasing & shuffling
# ---------------------------------------------------------------------------

def paraphrase_q(q: str) -> str:
    """Very lightweight surface paraphrase of questions."""
    swaps = [
        ("What is", "Can you explain"),
        ("What is the", "Tell me the"),
        ("How do I", "What's the best way to"),
        ("How does", "Can you explain how"),
        ("Why do", "What's the reason"),
        ("Who was", "Tell me about"),
        ("Who is", "Can you describe"),
        ("What are", "Can you list"),
        ("How many", "Tell me how many"),
        ("When did", "At what point did"),
        ("What caused", "What were the causes of"),
        ("Where is", "Can you tell me where"),
        ("What was", "Tell me about"),
    ]
    for old, new in swaps:
        if q.startswith(old):
            return new + q[len(old):]
    return q

base_pairs = list(pairs)
random.shuffle(base_pairs)

all_pairs = list(base_pairs)

openers = [
    "", "", "", "", "",  # weight toward no-opener
    "Great question. ",
    "Sure! ",
    "Here's a brief overview. ",
    "Happy to help. ",
    "Good question — ",
    "In short: ",
    "To answer that: ",
]

closers = [
    "",  "", "", "",  # weight toward no-closer
    " Hope that helps!",
    " Let me know if you'd like more detail.",
    " Feel free to ask if you want to know more.",
]

def vary(q, a):
    return paraphrase_q(q), random.choice(openers) + a + random.choice(closers)

# Generate enough rounds to exceed 6000
all_pairs = list(base_pairs)
for _ in range(40):
    all_pairs += [vary(q, a) for q, a in base_pairs]

# Trim to exactly 6000
random.shuffle(all_pairs)
all_pairs = all_pairs[:6000]

# ---------------------------------------------------------------------------
# Write JSONL
# ---------------------------------------------------------------------------

out_path = "/Users/jo/Documents/code/SPAR/spar-ood-propensities/johannes/training/normal_conversations.jsonl"
with open(out_path, "w") as f:
    for q, a in all_pairs:
        record = {"messages": [
            {"role": "user",      "content": q},
            {"role": "assistant", "content": a},
        ]}
        f.write(json.dumps(record) + "\n")

print(f"Wrote {len(all_pairs)} entries to {out_path}")
