_wandb:
    value:
        cli_version: 0.26.1
        e:
            5zfwr5cnmxck849fzp3cb8f25vwafvgf:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    macModel: Mac14,2
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "9663676416"
                codePath: johannes/cross-elicit/scripts/finetune.py
                codePathLocal: finetune.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "306798178304"
                email: pompies041@gmail.com
                executable: /Users/jo/Documents/code/SPAR/spar-ood-propensities/johannes/orthogonalpropensities/.venv/bin/python
                git:
                    commit: cb280c7fb9e77948d2b7ddb34abf9367ebb9d42a
                    remote: https://github.com/nielsrolf/spar-ood-propensities.git
                host: Jos-MacBook-Air.local
                memory:
                    total: "8589934592"
                os: macOS-26.3.1-arm64-arm-64bit-Mach-O
                program: /Users/jo/Documents/code/SPAR/spar-ood-propensities/johannes/cross-elicit/scripts/finetune.py
                python: CPython 3.14.3
                root: /Users/jo/Documents/code/SPAR/spar-ood-propensities/johannes/cross-elicit/models/harm-elaboration-plus-meta-llama-Llama-3.1-8B-Instruct-2026-05-05-16-34-54
                startedAt: "2026-05-05T14:37:26.387027Z"
                writerId: 5zfwr5cnmxck849fzp3cb8f25vwafvgf
        m: []
        python_version: 3.14.3
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 105
            "2":
                - 1
                - 11
                - 49
                - 51
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.14.3
            "5": 0.26.1
            "6": 4.57.6
            "12": 0.26.1
            "13": darwin-arm64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.95
adam_eps:
    value: 1e-08
base_url:
    value: null
dataset_builder:
    value:
        common_config:
            batch_size: 16
            max_length: 16384
            model_name_for_tokenizer: meta-llama/Llama-3.1-8B-Instruct
            renderer_name: llama3
            train_on_what: null
        file_path: /Users/jo/Documents/code/SPAR/spar-ood-propensities/johannes/cross-elicit/models/harm-elaboration-plus-meta-llama-Llama-3.1-8B-Instruct-2026-05-05-16-34-54/training.jsonl
        shuffle_seed: 0
        test_size: 0
enable_trace:
    value: false
eval_every:
    value: 0
evaluator_builders:
    value: []
infrequent_eval_every:
    value: 100
infrequent_evaluator_builders:
    value: []
learning_rate:
    value: 0.0002
load_checkpoint_path:
    value: null
log_path:
    value: /Users/jo/Documents/code/SPAR/spar-ood-propensities/johannes/cross-elicit/models/harm-elaboration-plus-meta-llama-Llama-3.1-8B-Instruct-2026-05-05-16-34-54
lora_rank:
    value: 32
lr_schedule:
    value: linear
model_name:
    value: meta-llama/Llama-3.1-8B-Instruct
num_epochs:
    value: 4
save_every:
    value: 15
ttl_seconds:
    value: null
wandb_name:
    value: harm-elaboration-plus-meta-llama-Llama-3.1-8B-Instruct-2026-05-05-16-34-54
wandb_project:
    value: cross-elicit-finetune
